### ISSUE TITLE
can't connect you less LS120-ELP1

### ISSUE THREAD

**Issue by 220v16a** [gruijter/com.gruijter.enelogic#14]
![IMG_3697](https://user-images.githubusercontent.com/49609369/56091253-f340b200-5eac-11e9-9941-e41985ed3670.jpeg)
Can't connect Youless LS120-ELp1 because the keyboard screen will block save button. Also i can't disable gas button (because i have stadsverwarming)

**Comment by gruijter** [comment]
What iphone are you on? You cannot scroll the window up? Or move the keyboard down (with the arrow down symbol)?

**Comment by 220v16a** [comment]
Hi Robin,

Iphone 7. Same issues on ipad

**Comment by gruijter** [comment]
I tried on my GF iPad. It acts a bit weird indeed, but when I do 'discover' I can then disable gas and press save. Device is then added correctly. Just stay off the password field. That seems to mess things up.

**Comment by 220v16a** [comment]
Strange indeed. Because on my iphone and ipad (ok an old one) button is also coverd by keyboard. Only Stroom teruglevering and Dal tarief i can change te buttons but everything else no way bescause the keyboard wil cover the buttons

**Comment by gruijter** [comment]
I have no clue what is causing that. As an alternative pairing method you can use this website: https://developer.athom.com/tools/pair

So at least you can get started with the app :)

**Comment by 220v16a** [comment]
Thanks. With developer modus. It works. Great! Thank you. Fijne zondag verder en niet te lang achter de computer ;-)
