### ISSUE TITLE
App does not show data p1

### ISSUE THREAD

**Issue by marcovdb007** [gruijter/com.gruijter.enelogic#15]
Hi, i’m using the youless120 and it’s connected with a p1 connection. 
Next to it i’ve installed your app on my homey but this app does not show any data. When i configure the ls120 E then it shows info. Can you please let me know what i can do to get data in the P1 app?

In the logging of your app i see these errors

![C4D34A2E-C4F8-46C0-9631-BFAA54CDF0E8](https://user-images.githubusercontent.com/52218762/60128615-56936e00-9793-11e9-9d2a-e42ef36ab4c6.png)
![142AB208-31C1-4768-8C89-5E61CC3DC315](https://user-images.githubusercontent.com/52218762/60128616-572c0480-9793-11e9-85e8-612ed991c45e.png)

**Comment by gruijter** [comment]
You need the EL firmware in your youless. I suspect you have other firmware installed.

http://www.youless.nl/downloads.html?file=tl_files/downloads/youless-firmware-1.4.2-EL.exe

**Comment by marcovdb007** [comment]
Hi Gruijter, thanks for your quick reply. This solved my problem. It’s now working.
