### ISSUE TITLE
Last homey update broke led ring

### ISSUE THREAD

**Issue by MrXCuci** [gruijter/com.gruijter.enelogic#17]
Homey Pro. Led ring screensaver from your app is broken since last update. I guess they changed something in the fix but broke your screensaver it seems.

**Comment by gruijter** [comment]
I know there was a ledring bug in the previous Homey fw, but this has been fixed again in 2.4.1. What version are you on?

**Comment by gruijter** [comment]
v2.5.4  is now waiting approval in the appstore. Youless package 2.2.1. Code optimizations. Ledring fix for Homey fw > 2.4.0.

**Comment by MrXCuci** [comment]
Homey fw 2.4.1 and youless app version 2.5.3 Awaiting approval of your app. Thanks in advance.
