### ISSUE TITLE
Enelogic ledring werkt niet meer

### ISSUE THREAD

**Issue by aldotromp** [gruijter/com.gruijter.enelogic#18]
Zoals besproken werkt de ledring niet meer met mijn enelogic p1 meter uitlezer.
Je had aangegeven dat deze momenteel niet vertegenwoordigd werdt in de app en dat je deze weer zal toevoegen.

Alvast mijn dank

Aldo Tromp

**Comment by gruijter** [comment]
Nieuwe versie is zojuist vrijgegeven. Je moet de enelogic p (oud) selecteren. Wil je hem svp testen en mij laten weten of het werkt?

**Comment by aldotromp** [comment]
Beste Robin

Hij werkt weer , fantastische en bedankt

Met vriendelijke groeten

Aldo Tromp.

**Comment by gruijter** [comment]
Top!
