### ISSUE TITLE
Card not showing actual "Gas" usage 

### ISSUE THREAD

**Issue by jeroenvano** [gruijter/com.gruijter.enelogic#2]
Thanks for your app, really like it. 

Just a small thing, in the device card the actual gas usage stays on "-". 
The actual gas usage is reported and triggered in flows, so it must be a small cosmetic update to have it correctly shown in the device card. 

Regards,
Jeroen

**Comment by gruijter** [comment]
Hi jeroen,

Thx for reporting. Are you using the enelogic or the youless driver? I am using the youless myself, and do not have the problem you describe. Do you see the gas usage in indights correctly? 

Note: actual gas usage is always from the previous hour due to the way that smartmeters report it.

**Comment by jeroenvano** [comment]
I am using the enelogic driver, this is what I mean:
![image](https://user-images.githubusercontent.com/20746351/33800544-2ad8ad5a-dd42-11e7-91be-00e1670f00a6.png)

Yes, there is gas usage reporting in Insights, also the tag shows the hour value. 

It is just not showing up in the device card.

**Comment by gruijter** [comment]
@jeroenvano I just uploaded a new version to Github. I went through the code, but didn't find anything conclusive that is causing your problem. I did make some changes though, so I hope this works for you. Could you check if it does and let me know?

Thx!
Robin

**Comment by jeroenvano** [comment]
@gruijter what is the difference between both apps (youless & enelogic)? Other then the name I cannot seem to find it ;)

Need to find some time this weekend to run your update. Will let you know asap.

**Comment by gruijter** [comment]
The enelogic app has support for the youless devices as well as the old Enelogic p1 device. The youless app doesn't support the enelogic device.

The youless app was originally developed by someone else, but he didn't have time to maintain it. So I took over the maintenance and made the youless driver part the same for both apps.

So you are right that the youless drivers of both apps are the same :)

But I only made the updates in the enelogic app now, so you can test them first.

**Comment by jeroenvano** [comment]
Hi Robin, installed v1.1.2, no change, last hour gas usage still not showing up in the device card.

**Comment by gruijter** [comment]
I have no clue :( You do have an enelogic device, right? I mean, not a youless device. Did you try to delete the device, delete the app and then reinstall and pair again?

**Comment by jeroenvano** [comment]
No I am using the Youless LS120 P1. Also installed the Youless app, same issue? Reinstalled and swapped between both apps different times

**Comment by gruijter** [comment]
Ah, I thought you were using the enelogic driver, but you apparently meant the enelogic app with the youless driver.

I just fixed some issues, but nothing very conclusive. New Enelogic app version is on Github. I tested with the LS120 myself, and for me the gas usage is working as it should. Please let me know if this works for you also. If so, I will also implement it in the youless app.

**Comment by gruijter** [comment]
And an additional remark: please check the cable between the LS120 and the smartmeter, and also try to reset the LS120 itself. I have seen the LS120 hanging up on a number of occasions, which required a hard reset of the LS120.

**Comment by jeroenvano** [comment]
The problem is now solved. I did not reset the LS120 , your fixed version did the work,

**Comment by gruijter** [comment]
Super! Thx for reporting.
