### ISSUE TITLE
Gas icons not showing

### ISSUE THREAD

**Issue by mhoogenbosch** [gruijter/com.gruijter.enelogic#20]
Don’t know if this is normal but just noticed it. 

![AE9C59B5-3612-4B15-8393-BBD5E3A55DAE](https://user-images.githubusercontent.com/36899598/79078297-c87b7a80-7d07-11ea-8547-c34bad67dfaf.jpeg)

**Comment by gruijter** [comment]
All good here. Maybe restart the app or ptp Homey?

![Screenshot_20200412-215452_Homey](https://user-images.githubusercontent.com/19174120/79078415-7dae3280-7d08-11ea-904c-40ccea9319b6.jpg)

**Comment by mhoogenbosch** [comment]
Weird, also on 4.2? I’ll ptp and report back.

Verstuurd vanaf mijn iPhone

Op 12 apr. 2020 om 21:57 heeft gruijter <notifications@github.com> het volgende geschreven:

﻿

All good here. Maybe restart the app or ptp Homey?

[Screenshot_20200412-215452_Homey]<https://user-images.githubusercontent.com/19174120/79078415-7dae3280-7d08-11ea-904c-40ccea9319b6.jpg>

**Comment by mhoogenbosch** [comment]
Right, wrong app.. sorry!

Verstuurd vanaf mijn iPhone

Op 12 apr. 2020 om 22:10 heeft Martijn Hoogenbosch <martijn@martijnhoogenbosch.nl> het volgende geschreven:

﻿ Weird, also on 4.2? I’ll ptp and report back.

Verstuurd vanaf mijn iPhone

Op 12 apr. 2020 om 21:57 heeft gruijter <notifications@github.com> het volgende geschreven:

﻿

All good here. Maybe restart the app or ptp Homey?

[Screenshot_20200412-215452_Homey]<https://user-images.githubusercontent.com/19174120/79078415-7dae3280-7d08-11ea-904c-40ccea9319b6.jpg>
