### ISSUE TITLE
Youless Water

### ISSUE THREAD

**Issue by Ramonzuidgeest** [gruijter/com.gruijter.enelogic#22]
Since a couple of days one of my YouLess is not reporting data to Homey. The youless that is reading mij water usage witch the optical sensor is not sending data.
The other is on the P1 port of the smart power meter, thisone is working great.
Homey 7.2.0
App version 4.0.0. (both experimental and def)

**Comment by gruijter** [comment]
Ok, guess I need to check the optical driver then. Can you send me an app diagnostics report?

**Comment by Ramonzuidgeest** [comment]
I dit make the report.Number 24009d74-2e29-43e6-bc77-338345e09378Greetings Ramon Op 1 dec. 2021 21:05 schreef gruijter ***@***.***>:
Ok, guess I need to check the optical driver then. Can you send me an app diagnostics report?

**Comment by gruijter** [comment]
v4.0.1 should fix it. Thx for reporting, and let me know if you find any other issues.

**Comment by Ramonzuidgeest** [comment]
Wow,Thanks fot the Quick Solution! Greetings Ramon Op 2 dec. 2021 10:01 schreef gruijter ***@***.***>:
v4.0.1 should fix it. Thx for reporting, and let me know if you find any other issues.
