### ISSUE TITLE
Dal en piek verkeerd

### ISSUE THREAD

**Issue by Willemss001** [gruijter/com.gruijter.enelogic#23]
Beste,

Onlangs Youless LS120 aangekocht en aangesloten op de P1 poort van men digitale teller. Fantastisch product en mooi inzicht van energieverbruik -opbrengst via de Youless app.
Zonet met Homey gekoppeld maar helaas Haalt deze dag en nachttarief door elkaar.. Youless app geeft het wel goed. Import 1 = dagtarief.. Import 2 = nachttarief. Idem met export.
Doe ik iets mis? Instelling verkeerd?

Alvast bedankt!

Mvg,
Stefan

![FB4451CA-34EC-4781-8A76-00631886EEDF](https://user-images.githubusercontent.com/95571541/144750538-39c2019c-415b-4020-809a-1ee6f2208076.jpeg)
![4029BCA9-0A5C-4F0F-B45F-52896295C331](https://user-images.githubusercontent.com/95571541/144750540-33820e27-784f-48a7-8783-f3e3baf06e09.jpeg)

**Comment by gruijter** [comment]
Are you maybe in Belgium? For Belgium the day/night is reversed compared to The Netherlands

https://youless.nl/blogpost/items/ls120-fw143-vlaanderen.html

If so I might need to add a switch in the device settings to reverse the values.

**Comment by Willemss001** [comment]
Thanks for getting back to me and yes, I'm from Belgium. Applogies I wrote previous message in Dutch..tought you were from the Netherlands. 😉
Yes, that switch to reverse those values would greatly appreciated! 👍
Many thanks!
Take care

**Comment by gruijter** [comment]
I'm Dutch, but I like to keep communication here and at the forum in English so others can join and learn.

I'll make a switch in a next app release.

**Comment by Willemss001** [comment]
Understood and thanks! 👍

**Comment by gruijter** [comment]
Fixed in 4.1.0 . You can now select to reverse the meters in the advanced device settings.
