### ISSUE TITLE
Eneogic P1 device stopped working, reading shows "session.on is not a function..

### ISSUE THREAD

**Issue by kay-arne** [gruijter/com.gruijter.enelogic#24]
After the app was updated (to the new SDK?) my Homey lost its connection to the Eneogic P1 device.
I removed the device from Homey and tried to add it again but after choosing the Enelogic P1 device the installation proces shows the error "session.on is not a function" and stops.

**Comment by gruijter** [comment]
See forum for a solution :)

https://community.homey.app/t/app-pro-youless-enelogic-pvoutput-belgian-and-dutch-p1-smart-meter-reader/4235/256

**Comment by kay-arne** [comment]
I missed that, sorry. The 4.0.3. version works! Thnx for your (very) quick response.
