### ISSUE TITLE
P1 and S0 to Homey

### ISSUE THREAD

**Issue by HenkN** [gruijter/com.gruijter.enelogic#26]
Hi, I want to use one youless for connection to P1 and for connection with Solar panel via S0-pulses. In Homey I add a LS120-P1-> okay. When I add a LS120-S0 on the same ip-address, I get an error. What can I do?

Would be nice to include the S0 input in the P1 configuration. So one device with both P1 info and S0 info from a selectable device (eg solar panel or water meter). 
I have now an old Homewizard Energylink on the Homey with the same capabilities. In one app the P1 info and S0 solarpanel info. Also a nett power consumption (power from grid plus power from PV). Very nice option.

**Comment by gruijter** [comment]
What does the log say? I have s0 and p1 both connected to Homey without problem.
