### ISSUE TITLE
The LedRing is not compatible / working on the new Homey Pro (Early 2023)

### ISSUE THREAD

**Issue by alexm83** [gruijter/com.gruijter.enelogic#28]
The LED ring does not work with the new homey.
Is it something I can fix myself?

The log says:
TypeError: this.animation.updateFrames is not a function at Ledring.change (/app/ledring.js:82:19

**Comment by gruijter** [comment]
in HP2023 the LED ring is not controllable anymore from an app. Athom decided that way :(
