### ISSUE TITLE
Enologic

### ISSUE THREAD

**Issue by aldotromp** [gruijter/com.gruijter.enelogic#3]
beste ...

na de update van ongeveer 2 weken geleden werkt mijn app niet meer met de P1 device van enologic .
Hij geeft een foutmelding omdat hij geen gas waarden binnen krijgt.
Nu woon ik in almere en heb hier dus gen gas.
de foutmelding is:

error parsing gas information.

is hier wat aan te doen ?

Vandaag ook een update binnen gehad, maar ook nu de zelfde fout melding.

Aldo

**Comment by gruijter** [comment]
Hi Aldo,

I have no Enelogic P1 myself to test with. Would it be possible for you to provide remote access to your device? You would then have to do portforwarding in your router of port 1000 to the enelogic device, and provide me your external ip address.

If this is all abracadabra to you I guess I'll have to find another user to test with.

**Comment by aldotromp** [comment]
Het is me niet gelukt
Ik wacht wel af of er ooit een update komt waarbij gas niet verplicht is

Met vriendelijke groeten

Aldo Tromp.
