### ISSUE TITLE
Ls120- Pairing but no connection

### ISSUE THREAD

**Issue by Andi-RK** [gruijter/com.gruijter.enelogic#30]
Hey Guys,

this is my first Issue, nice to meet you all. I today received my Homey Pro early 2023 and - amongst others - instaled the youless app. Pairing as P1 with both of my youless ls120 was possible without issues. But seconds after having paired the devices, the status changed to „no connection“. Has anyone an idea what can be the cause of this? None of the other devices (hue, Shelly, tv) showed such a behavior.

It would be great if anyone managed to operate the devices with homey 2023. 

Thanks in advance 

Andi

**Comment by gruijter** [comment]
Hi Andi,

On the forum there are more people watching and able to support: https://community.homey.app/t/app-pro-youless-enelogic-pvoutput-belgian-and-dutch-p1-smart-meter-reader/4235

But the problem could be related to several things. The ip address of the youless could be changing if you did nit set a fixed ip in your router. Also it could be that you are using old/wrong firmware in the youless.
In the app logs you might find a hint to the cause of the issue.

**Comment by Andi-RK** [comment]
Thank you gruijter,

Indeed, there was an update available. For none of both devices it was successful and even worse they refuse to communicate and (!) the reset procedure initiated by 5 times disconnecting the Ethernet does not start at any device. I asked the Costumers support what to do to reset the device. I will then make the update and report ;)

have a great Weekend

**Comment by Andi-RK** [comment]
A short update. With the assistance of the Costumers support one of the devices is operational again. I also updated to 1.5.3 (both options) but there is still no communication with homey… any ideas?

**Comment by Andi-RK** [comment]
Hey Gruijter, 

I had some contact with the Support to also fix the 2nd device. They said possibly you can make use of some further info. The message homey sends is that there is no connection to smart meter. Homey is aware when the device is off as it then says connect ehostunreach. 

I am located in Germany with our low-capability two way digital meter. In the App I can see the results of sensing the LED. 

This is what the support said:

The Homey plugin is a third party plugin, so I don't know details about the inner workings. It should be noted tough that the message you receive refers to the 'smart meter'. In the Netherlands, most meters have a special smart meter interface, and they have special data fields as extra information. It looks like the plugin is warning that these fields are not present, which is true because this is not available in Germany.

Can this support your analysis? It would be great if there is anything you can indicate to try here!

kind regards and habe a great evening

andi

**Comment by gruijter** [comment]
Hi Andi,

The Homey app was designed to work with the NL language -EL version firmware. In the past I made a change to support German language firmware. But that might have broken with newer firwares.
So you dont have a P1 interface in Germany, but you are using the optical sensor (flashing LED), correct?
In that case you must use the LS110/120E driver in Homey. Did you try that one when adding the device?

Or when you use the S0 interface (pulse counter wired to the green terminal block on the Youless), you must use the LS120S0 driver in Homey.

If you tried the correct driver, and still it fails, please create an app diagnostics report. Maybe the logs privide me more insights on what is going on.

**Comment by Andi-RK** [comment]
That’s it! Thanks! I was trying it but as this step asked me to input the IP manually I thought this is wrong cause declaring it as 120p immediately worked. 

Thank you very much, this was a great support for Newbie-me!

Cu

Andi
