### ISSUE TITLE
P1 reader: IP not recognized

### ISSUE THREAD

**Issue by Eilandgast** [gruijter/com.gruijter.enelogic#5]
The current version (v.2.0.5) does not recognize my Enelogic P1-reader anymore when I try to add the device. Message "No valid Enelogic information found".

**Comment by gruijter** [comment]
Hi @Eilandgast ,

Did you get my pm on slack? I would like to remotely debug, but need your help to do so.

**Comment by Eilandgast** [comment]
kom er morgen op terug.

Op di 2 okt. 2018 21:50 schreef gruijter <notifications@github.com>:

**Comment by Eilandgast** [comment]
Hallo @gruijter ,
please contact me for remote debug pjdewit@gmail.com

**Comment by Eilandgast** [comment]
hallo @gruijter,
Fixed it: IP adres in my Ziggo modem (CBN CH7465) was different from the number that Fing reported (.235 in stead of .234)
