### ISSUE TITLE
Invalid content-type. Expected application/json but received text/plain

### ISSUE THREAD

**Issue by Jozzle** [gruijter/com.gruijter.enelogic#6]
Added a newly bought Youless 120 P1 meter. Installed via P1 port and is operational (firmware 1.4.1-PO). 

After succesfully adding on Homey (1.5.12) the readings are fine. After a couple of minutes i see the following exception in the devices overview:

![youless 120](https://user-images.githubusercontent.com/2930363/47036833-a5592480-d17d-11e8-9ba8-14c0ac75c339.PNG)

No special settings.

**Comment by Jozzle** [comment]
While the first post is all business, I'd also like to thank you for your work so far! I'm really excited to get this working and that's only because of the work you put in already. Thanks!

**Comment by gruijter** [comment]
I suspect it is the firmware version. If you do not need PO, try to flash the EL (enelogic) version instead. That is what I use myself, and what the app was developped to work with. I never came around to check the differences with the PO version of the firmware.

You can get it here: www.youless.nl/downloads.html

**Comment by gruijter** [comment]
And thx for your moral support 😉

**Comment by Jozzle** [comment]
Ah yes, that was it  👍 PvOutput was a nice to have, alongside my solarpanel tracking, but wasn't sure if i wanted to share that publicly anyway. 

So thanks! Happy panda here :)
