### ISSUE TITLE
Error when password set on youless LS110

### ISSUE THREAD

**Issue by EDVDVD** [gruijter/com.gruijter.enelogic#9]
2019-01-21 19:59:08 [err] [ManagerDrivers] [LS110] [0] Parse Error 

Without password the device is added succesfull but with password the above error.
Youless firmware: 1.2.2-EL
Homey 2.0

**Comment by gruijter** [comment]
Ah, ok.yes with ls110 setting a password is indeed not working. This will probably never be supported on ls110. But is all working ok without a password?

**Comment by EDVDVD** [comment]
Ah ok, then i need to not use the password, thanks for the fast reply.

Verstuurd vanaf mijn iPad

Op 21 jan. 2019 om 21:01 heeft gruijter <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Ah, ok.yes with ls110 setting a password is indeed not working. This will probably never be supported on ls110. But is all working ok without a password?
